// You are given an array of integers a. A new array b is generated by rearranging the elements of a in the following way:

// b[0] is equal to a[0];
// b[1] is equal to the last element of a;
// b[2] is equal to a[1];
// b[3] is equal to the second-last element of a;
// b[4] is equal to a[2];
// b[5] is equal to the third-last element of a;
// and so on.
// Your task is to determine whether the new array b is sorted in strictly ascending order or not.

// Here is how the process of generating the new array b works:

function alternatingSort(a) {
  const b = []
  let j = a.length - 1
  let i = 0
  while(i <= j) {
    b.push(a[i])

    if (i != j) b.push(a[j])

    i++
    j--
  }
  console.log(b)
  return b.every((element, index) => element < b[index + 1] || [index === b.length - 1]);
}
